name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install root deps
        run: npm ci

      - name: Install backend deps
        run: npm ci
        working-directory: backend

      - name: Install frontend deps
        run: npm ci
        working-directory: frontend

      - name: Lint (frontend)
        run: npm run lint

      - name: Test backend (Jest)
        run: npm --prefix backend run coverage

      - name: Test frontend (Vitest)
        run: npm --prefix frontend run test:run

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: |
            backend/coverage
            frontend/coverage
          if-no-files-found: ignore
